# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'active_record_union', '~> 1.3'
gem 'activerecord-analyze', github: 'treycaliva/activerecord-analyze'
gem 'acts_as_list', '~> 0.9'
gem 'api-pagination', '~> 4.8'
gem 'aws-sdk-s3', '~> 1.21', require: false
gem 'bcrypt', '~> 3.1.7'
gem 'bcrypt_pbkdf', '~> 1.0'
gem 'blueprinter', '~> 0.6'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'chronic', '~> 0.10'
gem 'coffee-rails', '~> 4.2'
gem 'countries', '~> 2.1'
gem 'crypt_keeper', github: 'jmazzi/crypt_keeper'
gem 'dalli', '~> 2.7'
gem 'data_migrate', '~> 4.0'
gem 'doorkeeper', '~> 5.0'
gem 'dotenv-rails', '~> 2.5'
gem 'ed25519', '~> 1.2'
gem 'eu_central_bank', '~> 1.3'
gem 'faraday', '~> 0.15'
gem 'faraday-detailed_logger', '~> 2.1'
gem 'foreman', '~> 0.85'
gem 'health_check', '~> 3.0'
gem 'http-errors', '~> 0.1', require: 'http_error'
gem 'json-schema', '~> 2.8'
gem 'loofah', '>= 2.2.3'
gem 'mailgun-ruby', '~> 1.1'
gem 'mini_magick', '~> 4.8'
gem 'mjml-rails', '~> 4.2'
gem 'money-rails', '~> 1.11'
gem 'net-ssh', github: 'net-ssh/net-ssh'
gem 'newrelic_rpm', '~> 5.4'
gem 'oj', '~> 3.6'
gem 'pagy', '~> 0.19'
gem 'paper_trail', '~> 10.0'
gem 'paranoia', '~> 2.4'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'rack', '>= 2.0.6'
gem 'rack-cors', '~> 1.0'
gem 'rails', '~> 5.2'
gem 'redis', '~> 4.0'
gem 'redis-rack-cache', '~> 2.0'
gem 'redis-rails', '~> 5.0'
gem 'rollbar', '~> 2.17'
gem 'rswag-ui', '~> 2.0'
gem 'ruby_regex', '~> 0.1'
gem 'sass-rails', '~> 5.0'
gem 'seedbank', '~> 0.4'
gem 'sidekiq', '~> 5.2'
gem 'sidekiq-unique-jobs', '~> 6.0'
gem 'slim-rails', '~> 3.1'
gem 'uglifier', '~> 4.1'
gem 'whenever', '~> 0.10', require: false

# TODO: Move this to development/test group under RSpec testing, when ready to
#       go into production
gem 'factory_bot_rails'

# TODO: Move this to development/test group under Clean database when ready to
#       go into production
gem 'database_cleaner'

# TODO: Move this to development/test group under Clean database when ready to
#       go into production
gem 'faker'

group :development, :test do
  gem 'brakeman'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails'
end

group :test do
  gem 'action-cable-testing'
  gem 'hashie'
  gem 'rspec-its'
  gem 'rspec-sidekiq'
  gem 'rspec_junit_formatter', require: false
  gem 'rswag-specs', github: 'domaindrivendev/rswag'
  gem 'rubocop', require: false, github: 'rubocop-hq/rubocop'
  gem 'rubocop-rspec'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end

group :development do
  gem 'capistrano-newrelic'
  gem 'capistrano-rails'
  gem 'capistrano3-puma'
  gem 'guard-brakeman'
  gem 'guard-rspec', require: false
  gem 'guard-rubocop'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rack-mini-profiler'
  gem 'bullet'
end

group :production do
  gem 'seed_dump'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
